### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SalemTree** [alireza-montazeri/SofaTearing#1] opened 2022-10-09 08:40 UTC
I'm trying to build this plugin and having following error:
`[52/54] Building CXX object external_directories/ext_plugin_repo/SofaTearing/CMakeFiles/SofaTearing.dir/src/TearPlugin.cpp.o
FAILED: external_directories/ext_plugin_repo/SofaTearing/CMakeFiles/SofaTearing.dir/src/TearPlugin.cpp.o 
/usr/bin/clang++-12 -DNDEBUG -DSOFA_BUILD_SOFATEARING -DSOFA_BUILD_TEARING -DSofaTearing_EXPORTS -I/home/min/ext_plugin_repo/SofaTearing/src -Iinclude/SofaTearing -I/home/min/sofa/src/SofaKernel/modules/SofaCore/src -Iinclude/Sofa.Core -I/home/min/sofa/src/SofaKernel/modules/SofaHelper/src -Iinclude/Sofa.Helper -I/home/min/sofa/src/SofaKernel/modules/Sofa.Config/src -Iinclude/Sofa.Config -I/home/min/sofa/src/SofaKernel/modules/Sofa.Type/src -Iinclude/Sofa.Type -I/home/min/sofa/src/SofaKernel/modules/Sofa.Compat/src -Iinclude/Sofa.Compat -I/home/min/sofa/src/SofaKernel/modules/Sofa.Topology/src -Iinclude/Sofa.Topology -I/home/min/sofa/src/SofaKernel/modules/Sofa.Geometry/src -Iinclude/Sofa.Geometry -I/home/min/sofa/src/SofaKernel/modules/SofaDefaultType/src -Iinclude/Sofa.DefaultType -I/home/min/sofa/src/SofaKernel/modules/Sofa.LinearAlgebra/src -Iinclude/Sofa.LinearAlgebra -I/home/min/sofa/src/SofaKernel/modules/SofaBaseTopology/src -Iinclude/SofaBaseTopology -I/home/min/sofa/src/SofaKernel/modules/SofaSimulationCore/src -Iinclude/Sofa.SimulationCore -I/home/min/sofa/src/modules/SofaMiscFem/src -Iinclude/SofaMiscFem -I/home/min/sofa/src/SofaKernel/modules/SofaSimpleFem/src -Iinclude/SofaSimpleFem -I/home/min/sofa/src/SofaKernel/modules/SofaBaseLinearSolver/src -Iinclude/SofaBaseLinearSolver -I/home/min/sofa/src/SofaKernel/modules/SofaBaseMechanics/src -Iinclude/SofaBaseMechanics -isystem /home/min/sofa/src/SofaKernel/extlibs/json -isystem /usr/include/eigen3 -O2 -g -DNDEBUG -fPIC -Wno-attributes -Wall -W -Wno-padded -std=gnu++17 -MD -MT external_directories/ext_plugin_repo/SofaTearing/CMakeFiles/SofaTearing.dir/src/TearPlugin.cpp.o -MF external_directories/ext_plugin_repo/SofaTearing/CMakeFiles/SofaTearing.dir/src/TearPlugin.cpp.o.d -o external_directories/ext_plugin_repo/SofaTearing/CMakeFiles/SofaTearing.dir/src/TearPlugin.cpp.o -c /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:25:
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:25:
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.h:90:5: error: unknown type name 'Coord'
    Coord a;
    ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.h:91:5: error: unknown type name 'Coord'
    Coord b;
    ^
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:25:
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:129:13: error: missing 'typename' prior to dependent type name 'DataTypes::Coord'
            DataTypes::Coord stressDirection;
            ^~~~~~~~~~~~~~~~
            typename 
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:141:13: error: unknown type name 'Coord'
            Coord p[3];
            ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:157:25: error: unknown type name 'Coord'
                        Coord edgePointsPos[2];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:159:25: error: unknown type name 'Coord'
                        Coord edgeDirection = edgePointsPos[1] - edgePointsPos[0];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:181:25: error: unknown type name 'Coord'
                        Coord edgePointsPos[2];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:183:25: error: unknown type name 'Coord'
                        Coord edgeDirection = edgePointsPos[1] - edgePointsPos[0];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:207:25: error: unknown type name 'Coord'
                        Coord edgeDirection = p[j]-p[i];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:250:25: error: unknown type name 'Coord'
                        Coord edgePointsPos[2];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:252:25: error: unknown type name 'Coord'
                        Coord edgeDirection = edgePointsPos[1]-edgePointsPos[0];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:278:25: error: unknown type name 'Coord'
                        Coord edgePointsPos[2];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:280:25: error: unknown type name 'Coord'
                        Coord edgeDirection = edgePointsPos[1]-edgePointsPos[0];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:302:25: error: unknown type name 'Coord'
                        Coord edgePointsPos[2];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:304:25: error: unknown type name 'Coord'
                        Coord edgeDirection = edgePointsPos[1]-edgePointsPos[0];
                        ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:333:22: warning: unused variable 'incieseOk' [-Wunused-variable]
                bool incieseOk = triangleGeo->InciseAlongEdgeList(inciesEdge, new_points, end_points, reachBorder);
                     ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:58:94: warning: unused parameter 'currentForce' [-Wunused-parameter]
void TearPlugin<DataTypes>::addForce(const core::MechanicalParams* /*params*/, DataVecDeriv& currentForce, const DataVecCoord& /*currentPosition*/, const DataVecDeriv& /*currentVelocities*/)
                                                                                             ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:42:24: error: no matching member function for call to 'getContext'
    m_topology = this->getContext()->getMeshTopology(); // get the mesh topology to access to the points
                 ~~~~~~^~~~~~~~~~
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:40:32: note: in instantiation of member function 'sofa::component::forcefield::TearPlugin<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3, double>, sofa::type::Vec<3, double>, double>>::init' requested here
template class SOFATEARING_API TearPlugin<Vec3Types>;
                               ^
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.h:117:24: note: candidate function not viable: no known conversion from 'sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>' to 'const sofa::core::objectmodel::BaseObject' for object argument
    const BaseContext* getContext() const;
                       ^
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.h:119:18: note: candidate function not viable: no known conversion from 'sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>' to 'sofa::core::objectmodel::BaseObject' for object argument
    BaseContext* getContext();
                 ^
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:25:
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:53:5: error: cannot initialize object parameter of type 'sofa::core::behavior::SingleStateAccessor<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3, double>, sofa::type::Vec<3, double>, double>>' with an expression of type 'sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>'
    Inherit::init(); // call parent class init
    ^~~~~~~
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:26:
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.h:255:16: error: no viable conversion from returned value of type 'sptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3, double>, sofa::type::Vec<3, double>, double>>::MyType>' to function return type 'sptr<sofa::core::objectmodel::BaseObject::MyType>'
        return RealObject::create(instance, context, arg);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.h:338:85: note: in instantiation of member function 'sofa::core::ObjectCreator<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>::createInstance' requested here
        return addCreator(classname, templatename, ObjectFactory::Creator::SPtr(new ObjectCreator<RealObject>));
                                                                                    ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:38:10: note: in instantiation of function template specialization 'sofa::core::RegisterObject::add<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>' requested here
        .add<TearPlugin<Vec3Types> >(true);
         ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:67:5: note: candidate constructor not viable: no known conversion from 'typename TearPlugin<Vec3Types>::SPtr' (aka 'intrusive_ptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>') to 'sofa::core::objectmodel::BaseObject *' for 1st argument
    intrusive_ptr( T * p, bool add_ref = true ): px( p )
    ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:91:5: note: candidate constructor not viable: no known conversion from 'typename TearPlugin<Vec3Types>::SPtr' (aka 'intrusive_ptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>') to 'const boost::intrusive_ptr<sofa::core::objectmodel::BaseObject> &' for 1st argument
    intrusive_ptr(intrusive_ptr const & rhs): px( rhs.px )
    ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:115:5: note: candidate constructor not viable: no known conversion from 'typename TearPlugin<Vec3Types>::SPtr' (aka 'intrusive_ptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>') to 'boost::intrusive_ptr<sofa::core::objectmodel::BaseObject> &&' for 1st argument
    intrusive_ptr(intrusive_ptr && rhs) BOOST_SP_NOEXCEPT : px( rhs.px )
    ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:77:5: note: candidate template ignored: substitution failure [with U = sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>, sofa::core::objectmodel::BaseObject>'
    intrusive_ptr( intrusive_ptr<U> const & rhs, typename boost::detail::sp_enable_if_convertible<U,T>::type = boost::detail::sp_empty() )
    ^                                                                                                   ~~~~
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:131:5: note: candidate template ignored: substitution failure [with U = sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>, sofa::core::objectmodel::BaseObject>'
    intrusive_ptr(intrusive_ptr<U> && rhs, typename boost::detail::sp_enable_if_convertible<U,T>::type = boost::detail::sp_empty())
    ^                                                                                             ~~~~
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:25:
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.inl:25:
In file included from /home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.h:27:
In file included from /home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/behavior/ForceField.h:25:
In file included from /home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseForceField.h:25:
In file included from /home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/behavior/StateAccessor.h:26:
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.h:75:41: error: no viable conversion from 'sptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3, double>, sofa::type::Vec<3, double>, double>>::MyType>' to 'sptr<sofa::core::objectmodel::BaseObject>'
        if (context) context->addObject(obj);
                                        ^~~
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.h:255:28: note: in instantiation of function template specialization 'sofa::core::objectmodel::BaseObject::create<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>' requested here
        return RealObject::create(instance, context, arg);
                           ^
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.h:338:85: note: in instantiation of member function 'sofa::core::ObjectCreator<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>::createInstance' requested here
        return addCreator(classname, templatename, ObjectFactory::Creator::SPtr(new ObjectCreator<RealObject>));
                                                                                    ^
/home/min/ext_plugin_repo/SofaTearing/src/TearPlugin.cpp:38:10: note: in instantiation of function template specialization 'sofa::core::RegisterObject::add<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>' requested here
        .add<TearPlugin<Vec3Types> >(true);
         ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:67:5: note: candidate constructor not viable: no known conversion from 'typename TearPlugin<Vec3Types>::SPtr' (aka 'intrusive_ptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>') to 'sofa::core::objectmodel::BaseObject *' for 1st argument
    intrusive_ptr( T * p, bool add_ref = true ): px( p )
    ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:91:5: note: candidate constructor not viable: no known conversion from 'typename TearPlugin<Vec3Types>::SPtr' (aka 'intrusive_ptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>') to 'const boost::intrusive_ptr<sofa::core::objectmodel::BaseObject> &' for 1st argument
    intrusive_ptr(intrusive_ptr const & rhs): px( rhs.px )
    ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:115:5: note: candidate constructor not viable: no known conversion from 'typename TearPlugin<Vec3Types>::SPtr' (aka 'intrusive_ptr<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>>') to 'boost::intrusive_ptr<sofa::core::objectmodel::BaseObject> &&' for 1st argument
    intrusive_ptr(intrusive_ptr && rhs) BOOST_SP_NOEXCEPT : px( rhs.px )
    ^
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:77:5: note: candidate template ignored: substitution failure [with U = sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>, sofa::core::objectmodel::BaseObject>'
    intrusive_ptr( intrusive_ptr<U> const & rhs, typename boost::detail::sp_enable_if_convertible<U,T>::type = boost::detail::sp_empty() )
    ^                                                                                                   ~~~~
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:131:5: note: candidate template ignored: substitution failure [with U = sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<sofa::component::forcefield::TearPlugin<sofa::defaulttype::Vec3Types>, sofa::core::objectmodel::BaseObject>'
    intrusive_ptr(intrusive_ptr<U> && rhs, typename boost::detail::sp_enable_if_convertible<U,T>::type = boost::detail::sp_empty())
    ^                                                                                             ~~~~
/home/min/sofa/src/SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseContext.h:372:54: note: passing argument to parameter here
    virtual bool addObject( sptr<BaseObject> /*obj*/ )
                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
ninja: build stopped: subcommand failed.
`
any help would be appreciated

**Comment by alireza-montazeri** [comment] 2023-01-19 08:23
The problem is fixed in ee86cbc49b8c29ba60ada1e7ea82ff4664fedce5.

**Closed as completed by alireza-montazeri** 2023-01-19 08:23 UTC
